builds:
  - binary: score-compose
    main: ./cli/cmd/
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: score-compose
    homepage: "https://github.com/rachfop/score-compose"
    tap:
      owner: rachfop
      name: homebrew-score
    commit_author:
      name: rachfop
      email: prachford@icloud.com

checksum:
  name_template: "checksums.txt"
