before:
  hooks:
    - go mod tidy
builds:
  - binary: score-compose
    main: ./cli/
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
  - id: score-compose
    binary: score-compose
    main: ./cli
    ldflags:
      - -X github.com/score-spec/score-compose/internal/version.Version={{ .Version }}
      - -X github.com/score-spec/score-compose/internal/version.BuildTime={{ .CommitDate }}
      - -X github.com/score-spec/score-compose/internal/version.GitSHA={{ .FullCommit }}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64_v1
      - linux_arm64
      - windows_amd64_v1
      - darwin_amd64_v1
      - darwin_arm64

release:
  prerelease: auto

brews:
  - name: score-compose
    homepage: "https://github.com/rachfop/score-compose"
    tap:
      owner: rachfop
      name: homebrew-score
    commit_author:
      name: rachfop
      email: prachford@icloud.com

archives:
  - format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
