builds:
  - binary: score
    main: ./cli/
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: score-compose
    homepage: "https://github.com/rachfop/score-compose"
    tap:
      owner: rachfop
      name: homebrew-score
      branch: main
    commit_author:
      name: rachfop
      email: prachford@icloud.com
    license: "Apache 2.0"

checksum:
  name_template: "checksums.txt"
